Init tiller server side

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -131,7 +131,13 @@ staging:
     export API_REPLICAS=1
 
     echo "Checking Tiller..."
-    helm init --service-account tiller
+    helm init --service-account tiller --upgrade
+    kubectl rollout status -n "$TILLER_NAMESPACE" -w "deployment/tiller-deploy"
+    if ! helm version --debug; then
+      echo "Failed to init Tiller."
+      return 1
+    fi
+    echo ""
 
     helm upgrade --install \
       --wait \
