Test helm client

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -44,7 +44,8 @@ staging:
     - install_dependencies
     - ensure_namespace
     - create_secret
-    - deploy
+    - deploy || echo failed
+    - sleep 300
   environment:
     name: staging
     url: https://$STAGING_SUBDOMAIN.$AUTO_DEVOPS_DOMAIN/
@@ -131,7 +132,13 @@ staging:
     export API_REPLICAS=1
 
     echo "Checking Tiller..."
-    helm init --service-account tiller --upgrade
+    helm init --upgrade
+    helm list
+    kubectl rollout status -n "$TILLER_NAMESPACE" -w "deployment/tiller-deploy"
+    if ! helm version --debug; then
+      echo "Failed to init Tiller."
+      return 1
+    fi
     echo ""
 
     helm upgrade --install \
